const JOIN_CHAT = 'JOIN_CHAT';
const LEAVE_CHAT = 'LEAVE_CHAT';
const RECEIVE_USERS = 'RECEIVE_USERS';

const SEND_MESSAGE = 'SEND_MESSAGE';
const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';

export {
  JOIN_CHAT,
  LEAVE_CHAT,
  RECEIVE_USERS,
  SEND_MESSAGE,
  RECEIVE_MESSAGES,
};
