const JOIN_CHAT = 'JOIN_CHAT';
const LEAVE_CHAT = 'LEAVE_CHAT';
const RECEIVE_USERS = 'RECEIVE_USERS';

const SEND_MESSAGE = 'SEND_MESSAGE';
const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';

const WEBSOCKET_CONNECT = 'WEBSOCKET_CONNECT';
const WEBSOCKET_DISCONNECT = 'WEBSOCKET_DISCONNECT';
const WEBSOCKET_SEND = 'WEBSOCKET_SEND';

const WEBSOCKET_OPEN = 'WEBSOCKET_OPEN';
const WEBSOCKET_CLOSE = 'WEBSOCKET_CLOSE';
const WEBSOCKET_MESSAGE = 'WEBSOCKET_MESSAGE';

export {
  JOIN_CHAT,
  LEAVE_CHAT,
  RECEIVE_USERS,
  SEND_MESSAGE,
  RECEIVE_MESSAGES,
  WEBSOCKET_CONNECT,
  WEBSOCKET_DISCONNECT,
  WEBSOCKET_SEND,
  WEBSOCKET_OPEN,
  WEBSOCKET_CLOSE,
  WEBSOCKET_MESSAGE,
};
